import Link from "next/link";
import { Mark } from "@/components/brand/Mark";

export default function RiskDisclosurePage() {
  return (
    <div className="min-h-screen bg-void">
      <header className="border-b border-hairline px-6 py-4">
        <Link href="/" className="flex items-center gap-2">
          <Mark size={20} />
          <span className="text-sm font-semibold text-text-1">Tidevane</span>
        </Link>
      </header>
      <main className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed text-text-2">
        <h1 className="mb-6 text-xl font-medium text-text-1">Risk Disclosure</h1>

        <p className="mb-4">
          Trading derivatives, synthetic indices, and other instruments offered through
          Tidevane carries a high level of risk and can result in the loss of some or all
          of the funds in your account. You should not trade with money you cannot afford
          to lose.
        </p>

        <h2 className="mb-2 mt-8 font-medium text-text-1">Who you are trading with</h2>
        <p className="mb-4">
          Tidevane is not a broker, dealer, or financial institution. It is an interface
          and analysis layer built on Deriv's public API. Every trade executed through
          Tidevane is placed directly with Deriv (whichever Deriv entity your account is
          held with, based on your residence and account type). Deriv, not Tidevane, is
          the counterparty to your trades, holds your funds, and is responsible for your
          account's regulatory treatment, KYC, and withdrawals.
        </p>

        <h2 className="mb-2 mt-8 font-medium text-text-1">No guarantee of outcome</h2>
        <p className="mb-4">
          Statistics, estimates, and figures Tidevane displays — including any live
          volatility estimate, digit-distribution reading, or computed "fair value" —
          are measurements of present, historical, or modeled conditions. None of them
          are predictions of future price movement, and none constitute investment
          advice. A positive computed edge does not guarantee a winning trade, and a
          model flagged "valid" does not guarantee its assumptions will continue to
          hold. Past behavior of an instrument, including synthetic indices, is not a
          reliable indicator of its future behavior.
        </p>

        <h2 className="mb-2 mt-8 font-medium text-text-1">Automated trading</h2>
        <p className="mb-4">
          Tidevane's auto-trading feature executes real orders without a per-trade
          confirmation once you enable a strategy. You are solely responsible for any
          trades placed by a strategy you have enabled, for setting risk limits you are
          willing to accept, and for disabling a strategy if you no longer want it to
          trade on your behalf. Risk limits offered by Tidevane's auto-trading feature
          cap capital committed and trade frequency — they do not track or cap realized
          profit or loss.
        </p>

        <h2 className="mb-2 mt-8 font-medium text-text-1">Synthetic indices</h2>
        <p className="mb-4">
          Synthetic/derived indices are generated by Deriv's own simulation, not by a
          real market. They are not influenced by real-world news or economic events,
          but their statistical behavior is set entirely by Deriv and can change without
          notice. Tidevane's analysis of these instruments is based on observed
          statistical behavior and may not reflect changes Deriv makes to the underlying
          generator.
        </p>

        <p className="mt-10 text-xs text-text-3">
          This page is a plain-language summary, not legal advice, and has not been
          reviewed by a lawyer. It should be replaced with counsel-reviewed terms before
          this platform accepts real trading activity from the public.
        </p>
      </main>
    </div>
  );
}
